name: Create Repo

on:
  workflow_dispatch:
    inputs:
      author:
        required: true
        type: string
        description: Repo Owner
      email:
        required: true
        type: string
        description: Email Address
      choice:
        type: choice
        description: Type of Repo
        options:
          - Training Pipeline
          - Deploy ML Lambda Function
          - Deploy ML Webserver
          - Deploy ML Batch Process
          - Feature Store

jobs:
  create-repo:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python 3.8.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.0

      - name: Install cookiecutter
        run: |
          pip3 install cookiecutter

      - name: Cookiecutter Populate
        run: |
          '${{ inputs.choice }}' == 'Training Pipeline' && echo "Training Pipeline"
          '${{ inputs.choice }}' == 'Deploy ML Lambda Function' && echo "Deploy ML Lambda Function"
          '${{ inputs.choice }}' == 'Deploy ML Webserver' && echo "Deploy ML Webserver"
          '${{ inputs.choice }}' == 'Deploy ML Batch Process' && echo "Deploy ML Batch Process"
          '${{ inputs.choice }}' == 'Feature Store' && echo "Feature Store"

      - name: Greet
        id: greet
        run: |
          echo "choice is ${{ github.event.inputs.choice}}" / ${{ inputs.choice }}
